---

- name: Create dictionary with installation variant for HANA Client 
  set_fact:
    client: "{{ item }}"
  loop: "{{ components }}"
  when: item.component == 'hana_client'

- name: Install Hana Client on Linux 
  shell: "{{ hana_software_loc }}/{{ item.media_loc }}/{{ item.installer }} -a client -b --hostname={{ ansible_hostname }} --path={{ hana_client_install_path }}"
  loop: "{{ client.variants|flatten(levels=1) }}"
  when: item.os == 'LINUX'
