# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                      Playbook for HANA DB Install                           |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:          scs                                   # TODO: Replace this with new inventory group; Change to correct group

  name:           DB Installation - HANA
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:

  # - name: Test Connection                                     # Simple connection test for troubleshooting
  #   ping:




#----------------------------------------
# BEGIN
#
# TODO: evaluate for inclusion and refactor.
# SOURCE: sap-playbook
#----------------------------------------

# --------------------------------------+---------------------------------------8
#
# <Comment Header> 
#
# --------------------------------------+---------------------------------------8

#----------------------------------------
# BEGIN
#
# TODO: Port to general pacemaker section
#----------------------------------------

# # Only SLES support SBD fencing
# - hosts: iscsi
#   become: true
#   become_user: root
#   roles:
#    - role: iscsi-target-install
#      when:
#        - hana_database.size != "LargeInstance"
#        - hana_database.high_availability
#        - hostvars[hana_database.nodes[0].ip_admin_nic].ansible_os_family == 'Suse'

#----------------------------------------
# END
#----------------------------------------





...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
