# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                      Playbook for HANA DB Install                           |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:          scs                                   # TODO: Replace this with new inventory group; Change to correct group

  name:           DB Installation - HANA
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:

  # - name: Test Connection                                     # Simple connection test for troubleshooting
  #   ping:








...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
