# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                         PLAYBOOK FOR BOM PROCESSING                         |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:          "{{ sap_sid|upper }}_SCS"

  name:           BOM Processing
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


#---------------------------
#  BEGIN: Centiq
#---------------------------

# - hosts: scs
#   become: yes
#   vars:
#     tier: preparation
#   vars_files:
#     - "{{ inventory_dir }}/sap-system-config.yaml"
#   roles:
#     - role: dependencies-install                    # --> roles-sap/sap-packages        (playbook_02_os_sap_specific_config)
#     - role: disk-setup                              # --> roles-sap/sap-disk-setup      (playbook_02_os_sap_specific_config)
#     - role: swap-setup                              # --> roles-os/os-swap              (playbook_01_os_base_config)
#     - role: ensure-bom                              # --> roles-sap/bom-fetch
#     - role: process_bom                             # --> roles-sap/bom-processing
#     - role: sap-users                               # --> roles-sap/sap-users           (playbook_02_os_sap_specific_config)
#     - role: nfs-server-setup                        # --> roles-sap-os/nfs-server-setup

#---------------------------
#  END  : Centiq
#---------------------------


  tasks:

  - set_fact:
      tier:     preparation

  # - name: Test Connection                                     # Simple connection test for troubleshooting
  #   ping:

  - include_role:
      name:     roles-sap-os/sap-exports                        # TODO: Centiq copy (rework needed)

  - include_role:
      name:     roles-sap/bom-fetch                             # TODO: Centiq copy (rework needed)

  - include_role:
      name:     roles-sap/bom-processing                        # TODO: Centiq copy (rework needed)




#---------------------------
#  BEGIN: EXAMPLE
#---------------------------

# - hosts:        "{{ sapSid|lower }}scs00"
#   name:         test
#   remote_user:  ansible
#   become:       yes
#   become_user:  root
#   gather_facts: true
#   vars_files:
#     - vars/default.yaml


#   tasks:

#   - set_fact:
#       tier:     preparation

#   - include_role:
#       name: roles-sap/sapLvmSetup

#   - include_role:
#       name: roles-sap/sapMounts

#   - include_role:
#       name: roles-sap/sapPackages

#   - include_role:
#       name: roles-sap/sapExports

#   - include_role:
#       name: roles-sap/sapBom

#---------------------------
#  END  : EXAMPLE
#---------------------------


#----------------------------------------
# BEGIN
#
# TODO: evaluate for inclusion and refactor.
# SOURCE: sap-playbook
#----------------------------------------

# --------------------------------------+---------------------------------------8
#
# <Comment Header> 
#
# --------------------------------------+---------------------------------------8



#----------------------------------------
# BEGIN: Commented Section to enable BOM
#        Process
#
# TODO: evaluate and refactor. Depracate
#----------------------------------------

# # Mount Azure File share on all linux jumpboxes including rti
# - hosts: localhost:jumpboxes_linux
#   become: true
#   become_user: root
#   roles:
#     - role: mount-azure-files
#       when: output.software.storage_account_sapbits.file_share_name != ""

# # Mount Azure File share on all hanadbnodes. When the scenario is Large Instance, this task will be skipped
# - hosts: hanadbnodes
#   become: true
#   become_user: root
#   roles:
#     - role: mount-azure-files
#       when:
#         - output.software.storage_account_sapbits.file_share_name != ""
#         - hana_database.size != "LargeInstance"

# # Download SAP Media on Azure File Share
# - hosts: localhost
#   become: true
#   become_user: root
#   roles:
#     - role: sap-media-download

# - hosts: hanadbnodes
#   become: true
#   become_user: root
#   roles:
#     - role: sap-media-transfer
#       when: hana_database.size == "LargeInstance"
#     - role: large-instance-environment-setup
#       when: hana_database.size == "LargeInstance"

#----------------------------------------
# END
#----------------------------------------






...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
