# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                      Playbook for SAP DB Load                               |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---

- hosts:          "{{ sap_sid|upper }}_PAS"

  name:           SAP Installation - DB Load
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:

  # - name: Test Connection                                     # Simple connection test for troubleshooting
  #   ping:








...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
