---

- name: Check required variables are present and not empty
  assert:
    that:
      - "sapbits_location_base_path is defined"
      - "sapbits_location_base_path | trim | length != 0"
      - "bom_base_name is defined"
      - "bom_base_name | trim | length != 0"
      - "target_media_location is defined"
      - "target_media_location | trim | length != 0"
