# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                       Role for downloading the BOM                          |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---
# --------------------------------------+---------------------------------------8
#
# <Comment Header> 
#
# --------------------------------------+---------------------------------------8
# TODO: 20210127 Review

#----------------------------------------
# BEGIN - OLD CODE
#----------------------------------------

- include_tasks: pre_checks.yaml

- include_tasks: ensure-bom.yaml
