# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                            Package Installation                             |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---
# --------------------------------------+---------------------------------------8
#
# Task: 2.1       - Package Installation for SAP
#
# TODO: split between OS and sap playbooks


- name:             2.1 - Import package list
  include_vars:     sap-packages.yaml

- name:             "2.1 - Install OS packages fro SAP: {{ ansible_os_family|upper }}-{{ ansible_distribution_major_version }}"
  package:
    name:           "{{ item }}" 
    state:          present
  loop:             "{{ packages[ansible_os_family|lower] }}"

# --------------------------------------+---------------------------------------8


...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +-------------------------------------4--------------------------------------*/
