# /*----------------------------------------------------------------------------8
# |                                                                             |
# |                 Role for downloading the files from the BOM                 |
# |                                                                             |
# +-------------------------------------4--------------------------------------*/
---
# --------------------------------------+---------------------------------------8
#
# <Comment Header> 
#
# --------------------------------------+---------------------------------------8
# TODO: 20210127 Review

#----------------------------------------
# BEGIN - OLD CODE
#----------------------------------------

- import_tasks: pre_checks.yaml

- include_tasks: "{{ iterator }}"
  vars:
    iterator: "./iterate_bom.yaml"
